# platform = multi_platform_all
# complexity = low
# strategy = disable
# reboot = false
# disruption = low
- name: Disable the Automounter
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27498-5
    - DISA-STIG-RHEL-07-020110
    - NIST-800-171-3.4.6
    - NIST-800-53-AC-19(a)
    - NIST-800-53-AC-19(d)
    - NIST-800-53-AC-19(e)
    - NIST-800-53-IA-3
    - disable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_autofs_disabled
  tasks:

    - name: Disable service autofs
      service:
        name: autofs
        enabled: 'no'
        state: stopped
      register: service_result
      failed_when: service_result is failed and ('Could not find the requested service'
        not in service_result.msg)
      when: ansible_virtualization_role != "guest" or ansible_virtualization_type
        != "docker"

    - name: Disable socket of service autofs if applicable
      service:
        name: autofs.socket
        enabled: 'no'
        state: stopped
      register: socket_result
      failed_when: socket_result is failed and ('Could not find the requested service'
        not in socket_result.msg)
      when: ansible_virtualization_role != "guest" or ansible_virtualization_type
        != "docker"
