apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  name: edit-jenkins
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
userNames:
- system:serviceaccount:jenkins:jenkins
