apiVersion: v1
kind: Template
metadata:
  name: remediations-classic-secret

parameters:
- name: CONTENT_SERVER_TOKEN
  description: Token for accessing content server
  required: true

objects:
- apiVersion: v1
  stringData:
    password: ${CONTENT_SERVER_TOKEN}
  kind: Secret
  metadata:
    name: content-server
  type: Opaque
