apiVersion: v1
kind: Template
metadata:
  name: remediations-redis-secret

parameters:
- name: REDIS_PASS
  description: Password securing the Redis instance
  generate: expression
  from: "[a-zA-Z0-9]{16}"

objects:

- apiVersion: v1
  kind: Secret
  stringData:
    password: ${REDIS_PASS}
  metadata:
    name: redis
  type: Opaque
