apiVersion: v1
kind: Template
metadata:
  name: remediations-dc

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: remediations
    name: remediations
  spec:
    replicas: 1
    selector:
      app: remediations
      deploymentconfig: remediations
    strategy:
      type: Rolling
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        labels:
          app: remediations
          deploymentconfig: remediations
      spec:
        containers:
        - image: remediations:latest
          imagePullPolicy: Always
          name: remediations
          ports:
          - containerPort: 9002
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange


