apiVersion: v1
kind: Template
metadata:
  name: remediations-is

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: remediations
    name: remediations
  spec:
    lookupPolicy:
      local: true
