apiVersion: v1
kind: Template
metadata:
  name: remediations-redis-secret

parameters:
- name: CONTENT_SERVER_TOKEN
  description: Token for accessing content server
  required: true
- name: REDIS_PASS
  description: Password securing the Redis instance
  generate: expression
  from: "[a-zA-Z0-9]{16}"

objects:
- apiVersion: v1
  stringData:
    password: ${CONTENT_SERVER_TOKEN}
  kind: Secret
  metadata:
    name: content-server
  type: Opaque

- apiVersion: v1
  kind: Secret
  stringData:
    password: ${REDIS_PASS}
  metadata:
    name: redis
  type: Opaque
