apiVersion: v1
kind: Template
metadata:
  name: remediations-dc

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: remediations
    name: remediations
  spec:
    replicas: 1
    selector:
      app: remediations
      deploymentconfig: remediations
    strategy:
      type: Rolling
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        labels:
          app: remediations
          deploymentconfig: remediations
      spec:
        containers:
        - image: remediations:latest
          imagePullPolicy: Always
          name: remediations
          ports:
          - containerPort: 9002
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2
          env:
          - name: ADVISOR_HOST
            value: http://insights-api.insights-qa.svc.cluster.local:9002
          - name: ADVISOR_AUTH
            valueFrom:
              secretKeyRef:
                key: password
                name: content-server
          - name: CONTENT_SERVER_HOST
            value: http://insights-api.insights-qa.svc.cluster.local:9002
          - name: CONTENT_SERVER_AUTH
            valueFrom:
              secretKeyRef:
                key: password
                name: content-server
          - name: VULNERABILITIES_HOST
            value: http://insights-api.insights-qa.svc.cluster.local:9002
          - name: VULNERABILITIES_AUTH
            valueFrom:
              secretKeyRef:
                key: password
                name: content-server
          - name: LOG_LEVEL
            value: trace
          - name: REDIS_ENABLED
            value: "true"
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: redis
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange


