apiVersion: v1
kind: Template
metadata:
  name: remediations-postgres

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: postgres
    labels:
      app: postgres
  spec:
    dockerImageRepository: "registry.access.redhat.com/rhscl/postgresql-96-rhel7"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: postgres
    name: postgres
  spec:
    replicas: 1
    selector:
      name: postgres
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          name: postgres
      spec:
        containers:
        - env:
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db
          image: postgres:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - pg_isready -h 127.0.0.1 -p 5432
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: postgres
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U postgres -q -d postgres -c
                'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgres
        from:
          kind: ImageStreamTag
          name: postgres:latest
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: postgres
    name: postgres
  spec:
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: postgres
    type: ClusterIP
