---
swagger: "2.0"
info:
  description: Insights Remediations Service
  version: "1"
  title: Insights Remediations
  contact:
    email: jozef@redhat.com
basePath: /r/insights/platform/remediations/v1
consumes:
  - application/json
produces:
  - application/json
  - text/plain
  - text/html
tags:
  - name: "generator"
    description: "Ansible Playbook Generator"
  - name: "remediations"
    description: "Stored Remediations"
  - name: "resolutions"
    description: "Information about available Ansible resolutions"
  - name: "diagnosis"
    description: "Host-specific detailed diagnosis information"


paths:
  /playbook:
    post:
      tags:
        - generator
      summary: Generate an Ansible Playbook
      description: Generates an Ansible Playbook based on input parameters
      operationId: generate
      produces:
        - text/vnd.yaml
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/PlaybookDefinition"
      responses:
        200:
          description: OK
          schema:
            type: string
        400:
          $ref: '#/responses/BadRequest'

  /remediations:
    get:
      tags:
        - remediations
      summary: List Remediations
      description: Provides information about Remediations
      operationId: listRemediations
      parameters:
        - $ref: '#/parameters/RemediationSort'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/RemediationList'
    post:
      tags:
        - remediations
      summary: Create Remediation
      description: Creates a new Remediation based on given information
      operationId: createRemediation
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediationInput'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/RemediationDetails'
        400:
          $ref: '#/responses/BadRequest'

  /remediations/{id}:
    get:
      tags:
        - remediations
      summary: Get Remediation
      description: Provides information about the given Remediation
      operationId: getRemediation
      parameters:
        - $ref: '#/parameters/RemediationId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/RemediationDetails'
        404:
          $ref: '#/responses/NotFound'
    patch:
      tags:
        - remediations
      summary: Update Remediation
      description: Updates the given Remediation
      operationId: patchRemediation
      parameters:
        - $ref: '#/parameters/RemediationId'
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediationInput'
      responses:
        200:
          description: OK
        400:
          $ref: '#/responses/BadRequest'
        404:
          $ref: '#/responses/NotFound'
    delete:
      tags:
        - remediations
      summary: Remove Remediation
      description: Removes the given Remediation
      operationId: deleteRemediation
      parameters:
        - $ref: '#/parameters/RemediationId'
      responses:
        204:
          $ref: '#/responses/Deleted'
        404:
          $ref: '#/responses/NotFound'

  /remediations/{id}/issues/{issue}:
    patch:
      tags:
        - remediations
      summary: Update Remediation Issue
      description: Updates the given Remediation Issue
      operationId: patchRemediationIssue
      parameters:
        - $ref: '#/parameters/RemediationId'
        - $ref: '#/parameters/IssueId'
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediationIssueIn'
      responses:
        200:
          description: OK
        400:
          $ref: '#/responses/BadRequest'
        404:
          $ref: '#/responses/NotFound'
    delete:
      tags:
        - remediations
      summary: Remove Remediation Issue
      description: Removes the given Issue from the Remediation
      operationId: deleteRemediationIssue
      parameters:
        - $ref: '#/parameters/RemediationId'
        - $ref: '#/parameters/IssueId'
      responses:
        204:
          $ref: '#/responses/Deleted'
        404:
          $ref: '#/responses/NotFound'

  /remediations/{id}/issues/{issue}/systems/{system}:
    delete:
      tags:
        - remediations
      summary: Remove Remediation Issue System
      description: Removes the given System from the Issue Remediation
      operationId: deleteRemediationIssueSystem
      parameters:
        - $ref: '#/parameters/RemediationId'
        - $ref: '#/parameters/IssueId'
        - $ref: '#/parameters/SystemId'
      responses:
        204:
          $ref: '#/responses/Deleted'
        404:
          $ref: '#/responses/NotFound'

  /resolutions/{issue}:
    get:
      tags:
        - resolutions
      summary: Resolution metadata
      description: Provides information about resolutions available for the given issue
      operationId: resolutions
      parameters:
        - $ref: '#/parameters/IssueId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Resolutions'
        404:
          description: Issue not known or Ansible resolution not available

  /diagnosis/{system}:
    get:
      tags:
        - diagnosis
      summary: host-specific diagnosis
      description: Provides host-specific diagnosis information
      operationId: diagnosis
      parameters:
        - $ref: '#/parameters/SystemId'
        - in: query
          name: remediation
          type: string
          format: uuid
          required: false
          description: Remediation identifier (uuid)

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Diagnosis'
        404:
          description: System not found


parameters:
  IssueId:
    in: path
    name: issue
    type: string
    required: true
    description: Issue identifier (e.g. `vulnerabilities:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074`)
  RemediationId:
    in: path
    name: id
    type: string
    required: true
    description: Remediation identifier
    format: uuid
  SystemId:
    in: path
    name: system
    type: string
    required: true
    description: System identifier
    format: uuid
  RemediationSort:
    in: query
    name: sort
    type: string
    description: Sort order
    enum: [updated_at, -updated_at, name, -name, 'system_count', '-system_count', 'issue_count', '-issue_count']
    default: -updated_at


responses:
  BadRequest:
    description: Bad Request
    schema:
      type: object
      additionalProperties: false
      required: [errors]
      properties:
        errors:
          type: array
          items:
            type: object
            additionalProperties: false
            required: [id, status, code, title]
            properties:
              id:
                type: string
              status:
                type: integer
                example: 400
              code:
                type: string
                example: UNKNOWN_SYSTEM
              title:
                type: string
                example: Unknown system identifier "abcd"
  Deleted:
    description: Entity was deleted
  NotFound:
    description: Entity Not Found


definitions:
  #
  # Common types
  #
  DateTime:
    type: string
    format: date-time

  ResolutionRisk:
    type: integer
    enum:
      - -1
      - 1
      - 2
      - 3
      - 4
    example: 2

  IssueId:
    type: string
    pattern: ^(advisor|vulnerabilities|compliance|test):[\w\d-_|:]+$
    example: vulnerabilities:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074

  SystemId:
    type: string
    format: uuid
    example: a8799a02-8be9-11e8-9eb6-529269fb1459

  ResolutionType:
    type: string
    example: fix
    default: fix

  RemediationId:
    type: string
    format: uuid
    example: 9197ba55-0abc-4028-9bbe-269e530f8bd5

  #
  # Input types
  #
  RemediationInput:
    type: object
    additionalProperties: false
    x-remediations-strict: false # suppress validation since none of the properties is required
    properties:
      name:
        $ref: '#/definitions/RemediationName'
      auto_reboot:
        $ref: '#/definitions/RemediationAutoReboot'
      add:
        type: object
        additionalProperties: false
        required: [issues]
        properties:
          issues:
            type: array
            minItems: 1
            items:
              type: object
              additionalProperties: false
              required: [id]
              properties:
                id:
                  $ref: '#/definitions/IssueId'
                resolution:
                  $ref: '#/definitions/ResolutionType'
                systems:
                  type: array
                  items:
                    $ref: '#/definitions/SystemId'
          systems:
            type: array
            items:
              $ref: '#/definitions/SystemId'
        example:
          issues:
            - id: vulnerabilities:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074
              resolution: mitigate
              systems:
                - a8799a02-8be9-11e8-9eb6-529269fb1459

  RemediationIssueIn:
    type: object
    additionalProperties: false
    required: [resolution]
    properties:
      resolution:
        type: string

  PlaybookDefinition:
    type: object
    additionalProperties: false
    required: [issues]
    properties:
      issues:
        type: array
        minItems: 1
        example:
          - id: advisor:network_bond_opts_config_issue|NETWORK_BONDING_OPTS_DOUBLE_QUOTES_ISSUE
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
            resolution: mitigate
          - id: compliance:sshd_disable_root_login
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:CVE-2017-15126
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:CVE-2018-1087
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:CVE-2016-7913
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
        items:
          type: object
          additionalProperties: false
          required: [id, systems]
          properties:
            id:
              $ref: "#/definitions/IssueId"
            systems:
              type: array
              minItems: 1
              items:
                $ref: "#/definitions/SystemId"
            resolution:
              $ref: "#/definitions/ResolutionType"

  #
  # Output types
  #

  # System specific types
  SystemOut:
    type: object
    additionalProperties: false
    required: [id, hostname, display_name]
    properties:
      id:
        $ref: '#/definitions/SystemId'
      hostname:
        type: string
      display_name:
        type: string

  # Resolution specific types
  Resolutions:
    type: object
    additionalProperties: false
    required: [id, resolution_risk, resolutions]
    properties:
      id:
        $ref: "#/definitions/IssueId"
      resolution_risk:
        $ref: '#/definitions/ResolutionRisk'
      resolutions:
        type: array
        items:
          type: object
          additionalProperties: false
          required: [id, description, needs_reboot, resolution_risk]
          properties:
            id:
              $ref: '#/definitions/ResolutionType'
            description:
              type: string
              example: Disable DCCP kernel module
            needs_reboot:
              type: boolean
            resolution_risk:
              $ref: '#/definitions/ResolutionRisk'

  # Remediation specific types
  RemediationName:
    type: string
    example: Fix Critical CVEs

  RemediationAutoReboot:
    type: boolean
    description: Indicates whether systems that require reboot for the remediation to be properly applied should be rebooted automatically or not

  RemediationNeedsReboot:
    type: boolean
    description: Indicates whether any of the issues contained in the remediation require system reboot

  RemediationList:
    type: object
    additionalProperties: false
    required: [remediations]
    properties:
      remediations:
        type: array
        items:
          $ref: '#/definitions/RemediationListItem'

  RemediationListItem:
    type: object
    additionalProperties: false
    required: [id, name, owner, updated_at, issue_count, system_count, needs_reboot]
    properties:
      id:
        $ref: '#/definitions/RemediationId'
      name:
        $ref: '#/definitions/RemediationName'
      owner:
        type: integer
      updated_at:
        $ref: '#/definitions/DateTime'
        format: date-time
      issue_count:
        type: integer
      system_count:
        type: integer
      needs_reboot:
        type: boolean

  RemediationDetails:
    type: object
    additionalProperties: false
    required: [id, name, auto_reboot, owner, updated_at, issues]
    properties:
      id:
        type: string
        format: uuid
        example: 9197ba55-0abc-4028-9bbe-269e530f8bd5
      name:
        $ref: '#/definitions/RemediationName'
      needs_reboot:
        $ref: '#/definitions/RemediationNeedsReboot'
      auto_reboot:
        $ref: '#/definitions/RemediationAutoReboot'
      owner:
        type: integer
      updated_at:
        $ref: '#/definitions/DateTime'
      issues:
        type: array
        items:
          $ref: '#/definitions/RemediationIssue'

  RemediationIssue:
    type: object
    additionalProperties: false
    required: [id, description, resolution, systems]
    properties:
      id:
        $ref: '#/definitions/IssueId'
      description:
        type: string
      resolution:
        type: object
        additionalProperties: false
        required: [id, description, resolution_risk, needs_reboot]
        properties:
          id:
            type: string
          description:
            type: string
          resolution_risk:
            $ref: '#/definitions/ResolutionRisk'
          needs_reboot:
            type: boolean
      systems:
        type: array
        items:
          $ref: "#/definitions/SystemOut"

  # Diagnosis specific types
  Diagnosis:
    type: object
    additionalProperties: false
    required: [diagnosis]
    properties:
      diagnosis:
        type: object
        example:
          CVE_2018_1111_dhcp|ERROR_CVE_2018_1111_DHCP_2:
            dhcp_devs:
              - enp0s3
          CVE_2017_5753_4_cpu_kernel|KERNEL_CVE_2017_5753_4_CPU_ERROR_3:
            debugfs_available: true
            dmesg_available: true
            dmesg_wrapped: false
