swagger: "2.0"
info:
  description: Insights Remediations Service
  version: "1"
  title: Insights Remediations
  contact:
    email: jozef@redhat.com
basePath: /v1
consumes:
- application/json
produces:
- application/json
- text/html
tags:
- name: "generator"
  description: "Ansible Playbook Generator"
- name: "resolutions"
  description: "Information about available Ansible resolutions"

paths:
  /playbook:
    post:
      tags:
        - generator
      summary: Generate an Ansible Playbook
      description: Generates an Ansible Playbook based on input parameters
      operationId: generate
      produces:
      - text/vnd.yaml
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/PlaybookDefinition"
      responses:
        200:
          description: OK
          schema:
            type: string
        400:
          $ref: '#/responses/InvalidRequest'

  /resolutions/{issue}:
    get:
      tags:
        - resolutions
      summary: Resolution metadata
      description: Provides information about resolutions available for the given issue
      operationId: resolutions
      parameters:
        - $ref: '#/parameters/IssueId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Resolutions'
        404:
          description: Issue not known or Ansible resolution not available

parameters:
  IssueId:
    in: path
    name: issue
    type: string
    required: true
    description: Issue identifier (e.g. `vulnerabilities:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074`)

responses:
  InvalidRequest:
    description: invalid request
    schema:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

definitions:
  IssueId:
    type: string
    pattern: ^(advisor|vulnerabilities|compliance|test):[\w\d-_|:]+$
    example: vulnerabilities:CVE_2017_5461_nss|CVE_2017_5461_NSS_2

  SystemId:
    type: string
    example: a8799a02-8be9-11e8-9eb6-529269fb1459

  ResolutionType:
    type: string
    example: fix
    default: fix

  PlaybookDefinition:
    type: object
    additionalProperties: false
    required:
      - issues
    properties:
      issues:
        type: array
        minItems: 1
        example:
          - id: advisor:bond_config_issue|BOND_CONFIG_ISSUE
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
            resolution: mitigate
          - id: compliance:sshd_disable_root_login
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:RHSA-2018:0502
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:RHSA-2017:1852
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
          - id: vulnerabilities:RHBA-2007:0331
            systems:
              - a8799a02-8be9-11e8-9eb6-529269fb1459
              - 736ef48c-8f05-11e8-9eb6-529269fb1459
        items:
          type: object
          additionalProperties: false
          required:
            - id
            - systems
          properties:
            id:
              $ref: "#/definitions/IssueId"
            systems:
              type: array
              minItems: 1
              items:
                $ref: "#/definitions/SystemId"
            resolution:
              $ref: "#/definitions/ResolutionType"

  Resolutions:
    type: object
    properties:
      id:
        $ref: "#/definitions/IssueId"
      riskOfChange:
        $ref: '#/definitions/RiskOfChange'
      resolutions:
        type: array
        items:
          type: object
          properties:
            id:
              $ref: '#/definitions/ResolutionId'
            description:
              type: string
              example: Disable DCCP kernel module
            needsReboot:
              type: boolean
            riskOfChange:
              $ref: '#/definitions/RiskOfChange'

  ResolutionId:
    type: string
    example: 'fix'

  RiskOfChange:
    type: integer
    enum:
      - -1
      - 1
      - 2
      - 3
      - 4
    example: 2
