{{ if .Values.deploy.remediations }}
---
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  name: view-mnm
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: mnm-ci
userNames:
- system:serviceaccount:mnm-ci:default
{{ end }}
