{{ if .Values.deploy.cac }}
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: playbooks
  name: playbooks-cac
spec:
  replicas: 1
  selector:
    app: playbooks
    deploymentconfig: playbooks-cac
  strategy:
    type: Rolling
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      labels:
        app: playbooks
        deploymentconfig: playbooks-cac
    spec:
      containers:
      - image: "{{ .Values.imageRepo | default "docker-registry.default.svc:5000/buildfactory" }}/playbooks-cac:latest"
        imagePullPolicy: Always
        name: playbooks-cac
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /playbooks
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
{{ end }}
