deploy:
  redis: true
  postgres: false
  remediations: true
  ssg: true

imageRegistry: 172.30.217.42:5000
imageNamespace: remediations-stage

remediations:
  # Command to use for db migration. In stable environments this should be "npm run db:create; npm run db:migrate"
  migrationCommand: "npm run db:create; npm run db:migrate"

  strategy: Rolling
  imageChangeTrigger: true
  istag: prod
  replicas: 2
  autoscaling:
    min: 2
    max: 5


  logLevel: trace
  cloudwatch: true

  pathPrefix: /api

  db:
    ca: rds-client-ca

  advisor:
    impl: impl
    host: http://insights-advisor-api.advisor-prod.svc.cluster.local:8000
  compliance:
    impl: impl
    host: http://compliance-backend.compliance-prod.svc.cluster.local:3000
  contentServer:
    host: http://content-server.advisor-prod.svc.cluster.local:8080
  inventory:
    impl: impl
    host: http://insights-inventory.platform-prod.svc.cluster.local:8080
  patchman:
    impl: mock
  rbac:
    impl: impl
    host: http://rbac.rbac-prod.svc.cluster.local:8080
  receptor:
    impl: impl
    host: http://receptor-controller.platform-prod.svc.cluster.local:9090
  sources:
    impl: impl
    host: http://sources-api.sources-prod.svc.cluster.local:8080
  ssg:
    impl: impl
    host: http://playbooks-ssg:8080
  users:
    impl: impl
    host: https://backoffice-proxy-insights-services.ext.us-east.dc.prod.paas.redhat.com
  vulnerabilities:
    impl: impl
    host: http://vulnerability-engine-manager.vulnerability-engine-prod.svc.cluster.local:8443

ssg:
  replicas: 2
  istag: prod

secrets:
  backoffice: false
  redis: false
