apiVersion: v1
kind: Template
metadata:
  name: playbooks-cac-svc

objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: playbooks
    name: playbooks-cac
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    sessionAffinity: None
    type: ClusterIP
    selector:
      deploymentconfig: playbooks-cac

