{{ if .Values.secrets.postgres }}
apiVersion: v1
kind: Secret
stringData:
  username: postgres
  password: {{ .Values.secrets.postgres }}
  hostname: postgres
metadata:
  name: remediation-db
type: Opaque
{{ end }}
